server:
  port: 8080
spring:
  data:
    mongodb:
      host: googlebookmongodb
#      host: localhost
      port: 27017
      database: GoogleBook
      
  kafka:
    binder:
      brokers:
        - kafka:19092
    consumer:
      bootstrap-servers: kafka:19092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: book-events-listener-group
      
    topic: "book-events"
    producer:
      bootstrap-servers: kafka:19092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
    admin:
      properties:
        bootstrap.servers: kafka:19092
      
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG